version: "3.9"

networks:
  public_network:
    driver: bridge

services:
  video-capture-service:
    build:
      context: ../../../../src/services/video-capture-service
      dockerfile: Dockerfile
    container_name: video-capture-service
    env_file:
      - ../../../../src/services/video-capture-service/.env
    volumes:
      - /mnt/e/korayzma/images/saved/defects:/images
    depends_on:
      - rabbitmq
    networks:
      - public_network

    restart: unless-stopped

  image-logging-service:
      build:
        context: ../../../../src/services/image-logging-service
        dockerfile: Dockerfile
      container_name: image-logging-service
      env_file:
        - ../../../../src/services/image-logging-service/.env
      volumes:
        - /mnt/e/temp/rylovo_automation:/image_root_folder
      depends_on:
        - rabbitmq
      networks:
        - public_network

      restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_container
    ports:
     - "5672:5672"
     - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "nc", "-z", "rabbitmq", "5672"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - public_network   # Публичная сеть для доступа к веб-интерфейсу

    restart: unless-stopped